services:
  notification-service:
    container_name: nest-notification-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    args:
      NOTIFICATION_SERVICE_PORT: ${NOTIFICATION_SERVICE_PORT:-3005}
    ports:
      - "${NOTIFICATION_SERVICE_PORT}:${NOTIFICATION_SERVICE_PORT}"
    environment:
      - RABBITMQ_URL=${RABBITMQ_URL}
      - NGINX_PRIVATE_HTTP_URL=${NGINX_PRIVATE_HTTP_URL}
      - RETRY_MAX_ATTEMPTS=${RETRY_MAX_ATTEMPTS:-3}
    env_file:
      - .env
    volumes:
      - .:/app
      - notification_node_modules:/app/node_modules
      - pnpm_store:/pnpm/store
    networks:
      - vuhieu-network
    depends_on:
      - rabbitmq
    command: pnpm run start:dev

networks:
  vuhieu-network:
    name: vuhieu-network

volumes:
  notification_node_modules:
  pnpm_store:
    name: pnpm_store
