FROM node:22-alpine

ARG NOTIFICATION_SERVICE_PORT

ENV PORT=${NOTIFICATION_SERVICE_PORT:-3005}

WORKDIR /app

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml ./
RUN pnpm install

COPY . .

EXPOSE ${PORT}

CMD ["pnpm", "run", "start:dev"]
