version: "3.8"
name: vuhieu

include:
  - path: ./shopping-cart-service/docker-compose.dev.yml
  - path: ./user-service/docker-compose.dev.yml
  - path: ./notification-service/docker-compose.dev.yml
  - path: ./product-catalog-service/docker-compose.dev.yml

  - path: ./api-gateway-service/docker-compose.dev.yml
  - path: ./nginx/docker-compose.dev.yml

services:
  rabbitmq:
    container_name: rabbitmq-dev
    image: rabbitmq:3-management
    ports:
      - "${RABBITMQ_PORT}:${RABBITMQ_PORT}" # AMQP port
      - "${RABITTMQ_MANAGEMENT_PORT}:${RABITTMQ_MANAGEMENT_PORT}" # Management UI
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - vuhieu-network
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  postgres-sql:
    image: postgres:16-alpine
    container_name: postgres-sql-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-super_admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-super_password_secret}
      POSTGRES_MULTIPLE_DATABASES: ${POSTGRES_MULTIPLE_DATABASES}
    ports:
      - '${DATABASE_PORT:-5432}:5432'
    networks:
      - vuhieu-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-multiple-databases.sh:/docker-entrypoint-initdb.d/init-multiple-databases.sh

networks:
  vuhieu-network:
    name: vuhieu-network

volumes:
  pnpm_store:
    name: pnpm_store
  rabbitmq_data:
    name: rabbitmq_data
  postgres-data:
    name: postgres-data
