version: '3.8'
name: vuhieu

include:
  - path: ./api-gateway-service/docker-compose.dev.yml
  - path: ./nginx/docker-compose.dev.yml
  - path: ./shopping-cart-service/docker-compose.dev.yml

networks:
  vuhieu-network:
    name: vuhieu-network

volumes:
  pnpm_store:
    name: pnpm_store