services:
  product-catalog-postgres:
    image: postgres:16-alpine
    container_name: product-catalog-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATABASE_NAME_PRODUCT_CATALOG:-product_catalog}
      POSTGRES_USER: ${DATABASE_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-postgres}
    ports:
      - '${DATABASE_PORT:-5432}:5432'
    volumes:
      - product-catalog-postgres-data:/var/lib/postgresql/data

  product-catalog-service:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        PRODUCT_CATALOG_PORT: ${PRODUCT_CATALOG_PORT:-3004}
        NGINX_PRIVATE_HTTP_URL: ${NGINX_PRIVATE_HTTP_URL:-http://nginx-private:8080}
        NODE_ENV: development
        
    container_name: nest-product-catalog-dev
    ports:
      - '${PRODUCT_CATALOG_PORT:-3004}:${PRODUCT_CATALOG_PORT:-3004}'
    networks:
      - vuhieu-network
    volumes:
      - .:/app
      - product_catalog_node_modules:/app/node_modules
      - pnpm_store:/pnpm/store
    command: pnpm --filter product-catalog-service start:dev
    depends_on:
      - product-catalog-postgres

networks:
  vuhieu-network:
    name: vuhieu-network

volumes:
  product-catalog-postgres-data:
  pnpm_store:
    name: pnpm_store