services:
  product-catalog-service:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        PRODUCT_CATALOG_PORT: ${PRODUCT_CATALOG_PORT:-3004}
        NGINX_PRIVATE_HTTP_URL: ${NGINX_PRIVATE_HTTP_URL:-http://nginx-private:8080}
        NODE_ENV: development
        
    container_name: nest-product-catalog-dev
    ports:
      - '${PRODUCT_CATALOG_PORT:-3004}:${PRODUCT_CATALOG_PORT:-3004}'
    networks:
      - vuhieu-network
    volumes:
      - .:/app
      - product_catalog_node_modules:/app/node_modules
      - pnpm_store:/pnpm/store
    env_file:
      - .env
    command: pnpm --filter product-catalog-service start:dev
    depends_on:
      - postgres-sql

networks:
  vuhieu-network:
    name: vuhieu-network

volumes:
  pnpm_store:
    name: pnpm_store