services:
  api-gateway-service:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        API_GATEWAY_PORT: ${API_GATEWAY_PORT:-3000}
        NGINX_PRIVATE_HTTP_URL: ${NGINX_PRIVATE_HTTP_URL:-http://nginx-private:8080}
        RABBITMQ_URL: ${RABBITMQ_URL:-amqp://guest:guest@rabbitmq:5672}
        NODE_ENV: development
        
    container_name: nest-api-gateway-dev
    ports:
      - '${API_GATEWAY_PORT:-3000}:${API_GATEWAY_PORT:-3000}'
    networks:
      - vuhieu-network
    volumes:
      - .:/app
      - api_gateway_node_modules:/app/node_modules
      - pnpm_store:/pnpm/store
    command: pnpm --filter api-gateway-service start:dev
    depends_on:
      - shopping-cart-service
      - user-service
      - product-catalog-service
      - rabbitmq


networks:
  vuhieu-network:
    name: vuhieu-network

volumes:
  api_gateway_node_modules:
  pnpm_store:
    name: pnpm_store