FROM node:22-alpine

ARG SHOPPING_CART_PORT
ARG NODE_ENV

ENV PORT=$SHOPPING_CART_PORT
ENV NODE_ENV=$NODE_ENV

RUN npm install -g pnpm

WORKDIR /app

ENV PNPM_HOME=/pnpm
ENV PATH=$PNPM_HOME:$PATH
RUN pnpm config set store-dir /pnpm/store

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --ignore-scripts
RUN pnpm approve-builds @nestjs/core unrs-resolver
RUN pnpm install

COPY . .

EXPOSE $PORT

CMD ["pnpm", "run", "start:dev"]

