services:
  shopping-cart-service:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        SHOPPING_CART_PORT: ${SHOPPING_CART_PORT:-3002}
        NGINX_PRIVATE_HTTP_URL: ${NGINX_PRIVATE_HTTP_URL:-http://nginx-private:8080}
        NODE_ENV: development
        
    container_name: nest-shopping-cart-dev
    ports:
      - '${SHOPPING_CART_PORT:-3002}:${SHOPPING_CART_PORT:-3002}'
    depends_on:
      - postgres-sql
    networks:
      - vuhieu-network
    env_file:
      - .env
    volumes:
      - .:/app
      - shopping_cart_node_modules:/app/node_modules
      - pnpm_store:/pnpm/store
    command: pnpm --filter shopping-cart-service start:dev


networks:
  vuhieu-network:
    name: vuhieu-network

volumes:
  shopping_cart_node_modules:
  pnpm_store:
    name: pnpm_store