FROM nginx:alpine

ARG NGINX_PORT_PUBLIC
ENV NGINX_PORT=$NGINX_PORT_PUBLIC

RUN rm /etc/nginx/conf.d/default.conf

COPY ./nginx-public/nginx-public.conf /etc/nginx/nginx.conf

EXPOSE $NGINX_PORT

CMD ["nginx", "-g", "daemon off;"]