services:
  user-service:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        USER_PORT: ${USER_SERVICE_PORT:-3003}
        NGINX_PRIVATE_HTTP_URL: ${NGINX_PRIVATE_HTTP_URL:-http://nginx-private:8080}
        NODE_ENV: development
        
    container_name: nest-user-dev
    ports:
      - '${USER_SERVICE_PORT:-3003}:${USER_SERVICE_PORT:-3003}'
    depends_on:
      - postgres-sql
    networks:
      - vuhieu-network
    environment:
      DATABASE_HOST: postgres-sql
      DATABASE_PORT: 5432
      DATABASE_NAME: user_service
      DATABASE_USERNAME: user_service_user
      DATABASE_PASSWORD: user_service_password
      DATABASE_SYNC: true
    env_file:
      - .env
    volumes:
      - .:/app
      - user_node_modules:/app/node_modules
      - pnpm_store:/pnpm/store
    command: pnpm --filter user-service start:dev


networks:
  vuhieu-network:
    name: vuhieu-network

volumes:
  user_node_modules:
  pnpm_store:
    name: pnpm_store