FROM nginx:alpine

ARG NGINX_PORT_PRIVATE
ENV NGINX_PORT=$NGINX_PORT_PRIVATE

RUN rm /etc/nginx/conf.d/default.conf

COPY ./nginx-private/nginx-private.conf /etc/nginx/nginx.conf

EXPOSE $NGINX_PORT

CMD ["nginx", "-g", "daemon off;"]